language:
  - csharp
sudo:
  - required
mono:
  - latest
install:
  - sudo apt-get update -y
  - sudo bash install-python.sh
  - sudo apt-get install mono-devel mono-gmcs
  - cd /home/travis/build/johnypony3/choco
  - nuget restore src/chocolatey.sln
before_script:
  - chmod +x build.sh
  - chmod +x choco
  - sudo cp choco /usr/local/bin/choco
script:
  - ./build.sh -v
  - sudo mkdir -p /home/travis/build/johnypony3/choco/build_output/chocolatey/lib
  - sudo mkdir -p home/travis/build/johnypony3/choco/build_output/chocolatey/lib
  - sudo mono /home/travis/build/johnypony3/choco/build_output/chocolatey/choco.exe -? --allow-unofficial

#  - sudo choco -?
  - python ./github-parser.py
#  - choco apiKey -k $CHOCO_KEY -source https://chocolatey.org/
#  - find ./packages -name "*.nuspec" -type f #-exec cat {} \;
#  - choco pack ./packages/3.36.0/paket.nuspec
#  - mono /home/travis/build/johnypony3/choco/build_output/chocolatey/choco.exe pack ./packages/3.36.0/paket.nuspec
#  - find ./packages -name "*.nuspec" -type f -exec choco pack {} \;
#  - find . -name "*.nupkg" -type f #-exec cat {} \;
