language:
  - csharp
mono:
  - 3.12.0
install:
  - sudo apt-get install mono-devel mono-gmcs
  - nuget restore src/chocolatey.sln
before_script:
  - chmod +x build.sh
script:
  - ./build.sh -v
  - choco
#  - /System32/WindowsPowerShell/v1.0/powershell.exe ./generateAllPackages.ps1
