language:
  - csharp
sudo:
  - required
mono:
  - 3.12.0
install:
  - bash install-python.sh
  - sudo apt-get install mono-devel mono-gmcs
  - cd /home/travis/build/johnypony3/choco
  - nuget restore src/chocolatey.sln
before_script:
  - chmod +x build.sh
  - chmod +x choco
script:
  - ./build.sh -v
  - WORKDIR /usr/local/bin
  - RUN ln -s /home/travis/build/johnypony3/choco/build_output/chocolatey
  - COPY choco /usr/local/bin/choco
  - choco
#  - mono /home/travis/build/johnypony3/choco/build_output/chocolatey/choco.exe
#  - /System32/WindowsPowerShell/v1.0/powershell.exe ./generateAllPackages.ps1
