language:
  - csharp
sudo:
  - required
mono:
  - 3.12.0
install:
  - bash install-python.sh
  - sudo apt-get install mono-devel mono-gmcs
  - cd /home/travis/build/johnypony3/choco
  - nuget restore src/chocolatey.sln
before_script:
  - chmod +x build.sh
  - chmod +x choco
script:
  - ./build.sh -v
  - sudo mkdir -p /home/travis/build/johnypony3/choco/build_output/chocolatey/lib
  - sudo mkdir -p home/travis/build/johnypony3/choco/build_output/chocolatey/lib
  - python ./github-parser.py
  - choco -?
#  - mono /home/travis/build/johnypony3/choco/build_output/chocolatey/choco.exe apiKey -k $CHOCO_KEY -source https://chocolatey.org/
  - find ./packages -name "*.nuspec" -type f -exec cat {} \;
#  - find ./packages -name "*.nupkg" -type f -exec mono /home/travis/build/johnypony3/choco/build_output/chocolatey/choco.exe pack {} \;
