language:
  - csharp
sudo:
  - required
mono:
  - 3.12.0
install:
  - bash install-python.sh
  - sudo apt-get install mono-devel mono-gmcs
  - cd /home/travis/build/johnypony3/choco
  - nuget restore src/chocolatey.sln
before_script:
  - chmod +x build.sh
script:
  - ./build.sh -v
  - mono home/travis/build/johnypony3/choco/code_drop/chocolatey/console/choco.exe
#  - /System32/WindowsPowerShell/v1.0/powershell.exe ./generateAllPackages.ps1
